name: Build and push Docker images to dockerhub

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push api-gateway image
        uses: docker/build-push-action@v5
        with:
          context: ./Cafe_Management_System/api-gateway
          push: true
          tags: sodapopin/api-gateway:latest

      - name: Build and push customer-services image
        uses: docker/build-push-action@v5
        with:
          context: ./Cafe_Management_System/customer-services
          push: true
          tags: sodapopin/customer-services:latest

      - name: Build and push inventory-services image
        uses: docker/build-push-action@v5
        with:
          context: ./Cafe_Management_System/inventory-services
          push: true
          tags: sodapopin/inventory-services:latest
